services:
  mongodb:
    image: mongo
    container_name: yum-mongodb-container
    networks:
      - yum-server-net


  yum-recipe-app:
    image: ${IMAGE_NAME}
    container_name: yum-recipe-server-container
    depends_on:
      - mongodb
    networks:
      - yum-server-net

networks:
  network1:
    name: yum-server-net
    external: true
