spring:
  application:
    name: yum_recipe_server

  config:
    import: optional:file:.env[.properties]

springdoc:
  swagger-ui:
    use-root-path: true
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /api/recipes/v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  enable-spring-security: true

elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  port: ${ELASTICSEARCH_PORT}
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}